[package]
name = "jieba_vim_rs_test_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
jieba_vim_rs_test = { path = "../jieba_vim_rs_test" }
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
