[package]
name = "jieba_vim_rs_test"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11"
once_cell = "1.20"
assert_cmd = "2.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
minijinja = "2.5.0"
