[package]
name = "jieba_vim_rs_test_verifiable_case"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "2.0"
regex = "1.11"
once_cell = "1.20"
assert_cmd = "2.0"
jieba_vim_rs_test = { path = "../jieba_vim_rs_test" }
